import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import {AuthProvider}from '@/lib/context/AuthContext'

const raleway = Raleway({
    subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={raleway.className}>
      <body>
        <AuthProvider>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
